use master
create database QLBS
use QLBS
create table KHACHHANG
(
	MAKH INT identity (1,1) PRIMARY KEY ,
	HOTEN NVARCHAR(50),
	TAIKHOAN NVARCHAR(50),
	MATKHAU NVARCHAR(50),
	EMAIL NVARCHAR(100),
	DIACHI NVARCHAR(200),
	DIENTHOAI VARCHAR(50),
	GIOITINH NVARCHAR(3),
	NGAYSINH DATETIME
)
CREATE TABLE CHUDE
(
	MACHUDE int PRIMARY KEY,
	TENCHUDE NVARCHAR(50)
)
CREATE TABLE NXB
(
	MANXB INT PRIMARY KEY,
	TENNXB NVARCHAR(50),
	DIACHI NVARCHAR(200),
	DIENTHOAI VARCHAR(50)
)
CREATE TABLE TACGIA
(
	MATG INT PRIMARY KEY,
	TENTG NVARCHAR(50),
	DIACHI NVARCHAR(200),
	TIEUSU NVARCHAR(MAX),
	DIENTHOAI VARCHAR(50)
)
CREATE TABLE SACH
(
	MASACH INT PRIMARY KEY,
	TENSACH NVARCHAR(50),
	GIABAN DECIMAL(18,0),
	MOTA NVARCHAR(MAX),
	ANHBIA NVARCHAR(50),
	NGAYCAPNHAT DATETIME,
	SOLUONGTON INT,
	MANXB INT FOREIGN KEY REFERENCES NXB(MANXB),
	MACHUDE INT FOREIGN KEY REFERENCES CHUDE(MACHUDE)
)
CREATE TABLE THAMGIA
(
	MASACH INT NOT NULL FOREIGN KEY REFERENCES SACH(MASACH),
	MATG INT NOT NULL FOREIGN KEY REFERENCES TACGIA(MATG),
	VAITRO NVARCHAR(50),
	VITRI NVARCHAR(50),
)
ALTER TABLE THAMGIA 
ADD CONSTRAINT PK_TG_S PRIMARY KEY(MASACH,MATG)
CREATE TABLE DONHANG
(
	MADONHANG INT identity(1,1) PRIMARY KEY,
	DATHANHTOAN INT,
	TINHTRANGGH INT,
	NGAYDAT DATETIME,
	NGAYGIAO DATETIME,
	MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH)
)
CREATE TABLE CHITIETDONHANG
(
	MADONHANG INT NOT NULL FOREIGN KEY REFERENCES DONHANG(MADONHANG),
	MASACH INT NOT NULL FOREIGN KEY REFERENCES SACH(MASACH),
	SOLUONG INT,
	DONGIA INT,
)
ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT PK_CTDH_DH_S PRIMARY KEY(MADONHANG,MASACH)